version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - ./data/mongodb:/data/db
  backend:
    # https://blog.datepop.co.kr/docker-compose-fastapi/
    image: fastapi
    command: uvicorn app.main:app --host "0.0.0.0" --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - mongodb
